language: node_js

node_js:
  - "10.8.0"

env:
  global:
    - BASE_URL=arundo.com
    - NAMESPACE=fabric
    - CHARTS_REPO=charts

branches:
  only:
    - develop
    - /^v?\d+\.\d+\.\d+$/
    - /^cluster\-/

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install:
  - source .build/install.sh
  - source .service_config_envs
  - yarn --ignore -engines

script:
  - bash .build/build.sh || travis_terminate 1
  - bash .build/make_chart.sh
  - echo $BUILD_TYPE
  - helm install --name ${SERVICE_NAME}-${TRAVIS_COMMIT:0:8} --namespace $NAMESPACE .chart -f custom_values.yaml --dry-run --debug
  - if [[ $BUILD_TYPE =~ ^PR$ ]]; then
      helm install --name $SERVICE_NAME --namespace $NAMESPACE .chart --wait -f custom_values.yaml;
    fi;

after_script:
  - echo $BUILD_TYPE
  - if [[ $BUILD_TYPE =~ ^PR$ ]]; then
      yarn test;
    fi;

after_success:
  - if [[ $BUILD_TYPE =~ ^PR$ ]]; then
      helm del --purge $SERVICE_NAME;
    fi;

after_failure:
  - if [[ $BUILD_TYPE =~ ^PR$ ]]; then
      sleep 180;
      helm del --purge $SERVICE_NAME;
    fi;

deploy:
  provider: script
  script:
    - bash .build/deploy.sh
  verbose: true
  on:
    all_branches: true
  skip_cleanup: true

after_deploy:
  - if [[ $BUILD_TYPE =~ ^MERGE$ ]]; then
      bash .build/publish.sh;
    fi;

notifications:
  slack: arundo:QC3tXNL0ezWNGFbROfz57RcK
